# Generated by Django 4.2.4 on 2023-08-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.EmailField(max_length=320, primary_key=True, serialize=False)),
                ('fnames', models.CharField(max_length=38)),
                ('snames', models.CharField(max_length=38)),
                ('pii', models.FileField(upload_to='')),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
    ]
