# Generated by Django 4.2.4 on 2023-08-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlatRateBackend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
